### ISSUE TITLE
500 w/rc11

### ISSUE THREAD

**Issue by bmason** [damien-hl/nuxt3-auth-example#3]
Greetings

I am trying to get rc11 running under Windows.  It seems to start fine  'npm run dev'

  > Local:    http://localhost:3000/
  > Network:  http://10.15.4.230:3000/
  > Network:  http://192.168.0.14:3000/

 WARN  [@vue/reactivity-transform] Reactivity transform is an experimental feature.                           14:49:44
Experimental features may change behavior between patch versions.
It is recommended to pin your vue dependencies to exact versions to avoid breakage.
You can follow the proposal's status at https://github.com/vuejs/rfcs/discussions/369.

i Vite client warmed up in 1717ms                                                                             14:49:46
√ Nitro built in 806 ms

when I navigate to localhost:3000

500
request to http://[::]:3000/__nuxt_vite_node__/manifest failed, reason: connect ETIMEDOUT :::3000 ()

at async $fetchRaw2 (/C:/Projects/nuxt-strapi/3auth/node_modules/ohmyfetch/dist/shared/ohmyfetch.c2a48baf.mjs:132:20)
at async /C:/Projects/nuxt-strapi/3auth/.nuxt/dev/index.mjs:634:20
at async /C:/Projects/nuxt-strapi/3auth/.nuxt/dev/index.mjs:703:64
at async /C:/Projects/nuxt-strapi/3auth/.nuxt/dev/index.mjs:108:22
at async /C:/Projects/nuxt-strapi/3auth/node_modules/h3/dist/index.mjs:592:19
at async Server.nodeHandler (/C:/Projects/nuxt-strapi/3auth/node_modules/h3/dist/index.mjs:538:7)

**Comment by bmason** [comment]
The timeout error was caused by my windows misconfiguration.  Good example, thx.
